export {default as About} from './about'
export {default as Biography} from './biography'
export {default as Contact} from './contact'
export {default as Projects} from './projects'
export {default as Skills} from './skills'
export {default as Work} from './work'